### ISSUE TITLE
Python deb package should be called python-keyvi

### ISSUE THREAD

**Issue by david-cliqz** [cliqz/keyvi#17]
... and maybe the Python package could be renamed to keyvi too. Or is it too late (https://testpypi.python.org/pypi/pykeyvi)?

**Comment by hendrik-cliqz** [comment]
sounds reasonable. 

The python package is non-functional, I need to figure out how to package it for pip. Seems non-trivial.

**Comment by hendrik-cliqz** [comment]
The debian package is maintained here: https://github.com/hendrik-cliqz/keyvi-package

**Comment by hendrik-cliqz** [comment]
fixed in 0.1.3, updated README
